sudo: required
language: node_js
node_js:
  - '8'
env:
  - LOG_LEVEL=verbose
  - REGISTRY=https://registry.npmjs.org
script:
  - npm run lint
  - idev -V
  - npm run generate

deploy:
  provider: script
  skip_cleanup: true # 避免清空已安装的依赖
  script: npm run generate && npm run upload-oss
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|production$
