name: ci

on: [push]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo >>$GITHUB_ENV BRANCH_NAME=${GITHUB_REF#refs/heads/}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npm run lint
      - run: npm run publish:packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GIT_COMMIT_MESSAGE: ${{github.event.commits[0].message}}
      - run: npm run generate-and-deploy-oss
        env:
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          ACCESS_KEY_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}
          GIT_COMMIT_MESSAGE: ${{github.event.commits[0].message}}
